USE [master]
GO

/****** Object:  Database [nhl_db]    Script Date: 5/6/2021 8:39:33 PM ******/
DROP DATABASE [nhl_db]
GO

/****** Object:  Database [nhl_db]    Script Date: 5/6/2021 8:39:33 PM ******/
CREATE DATABASE [nhl_db]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'nhl_db', FILENAME = N'D:\rdsdbdata\DATA\nhl_db.mdf' , SIZE = 10240000KB , MAXSIZE = 10240000KB , FILEGROWTH = 10%)
 LOG ON 
( NAME = N'nhl_db_log', FILENAME = N'D:\rdsdbdata\DATA\nhl_db_log.ldf' , SIZE = 3828544KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [nhl_db].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [nhl_db] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [nhl_db] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [nhl_db] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [nhl_db] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [nhl_db] SET ARITHABORT OFF 
GO

ALTER DATABASE [nhl_db] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [nhl_db] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [nhl_db] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [nhl_db] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [nhl_db] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [nhl_db] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [nhl_db] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [nhl_db] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [nhl_db] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [nhl_db] SET  DISABLE_BROKER 
GO

ALTER DATABASE [nhl_db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [nhl_db] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [nhl_db] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [nhl_db] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [nhl_db] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [nhl_db] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [nhl_db] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [nhl_db] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [nhl_db] SET  MULTI_USER 
GO

ALTER DATABASE [nhl_db] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [nhl_db] SET DB_CHAINING OFF 
GO

ALTER DATABASE [nhl_db] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [nhl_db] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [nhl_db] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [nhl_db] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [nhl_db] SET QUERY_STORE = OFF
GO

ALTER DATABASE [nhl_db] SET  READ_WRITE 
GO


